/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jjz_jni_HelloJni */

#ifndef _Included_com_example_jjz_jni_HelloJni
#define _Included_com_example_jjz_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jjz_jni_HelloJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jjz_jni_HelloJni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
